{% set name = "propcache" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/propcache-{{ version }}.tar.gz
  sha256: 40d980c33765359098837527e18eddefc9a24cea5b45e078a7f3bb5b032c6ecf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - expandvars
    - setuptools >=47
    - tomli  # [py<311]
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - pytest.ini
  imports:
    - propcache
  commands:
    - pip check
    - pytest -v
  requires:
    - pip
    - pytest
    - pytest-cov >=2.3.1
    - pytest-xdist

about:
  home: https://github.com/aio-libs/propcache
  summary: Accelerated property cache
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aio-libs/propcache
  doc_url: https://propcache.readthedocs.io

extra:
  recipe-maintainers:
    - xhochy
