{% set name = "propcache" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01c4fc7480cd0598bb4b57022df55b9ca296da7fc5a8760bd8451a7e63a7d427

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3.1.4
    - expandvars
    - wheel
    - setuptools >=82.0.1
    - tomli  # [py<311]
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - pytest.ini
  imports:
    - propcache
  requires:
    - pip
    - pytest >=8.4.2
    - pytest-cov >=2.3.1
    - pytest-xdist
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/aio-libs/propcache
  summary: Accelerated property cache
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aio-libs/propcache
  doc_url: https://propcache.readthedocs.io
  description: The module provides a fast implementation of cached properties for Python 3.9+.

extra:
  recipe-maintainers:
    - xhochy
