{% set name = "propcache" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/propcache-{{ version }}.tar.gz
  sha256: f48107a8c637e80362555f37ecf49abe20370e557cc4ab374f04ec4423c97c3d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3.1.4
    - expandvars
    - wheel
    - setuptools >=47
    - tomli  # [py<311]
    - pip
  run:
    - python

test:
  source_files:
    - tests
    - pytest.ini
  imports:
    - propcache
  requires:
    - pip
    - pytest >=8.4.2
    - pytest-cov >=2.3.1
    - pytest-xdist
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/aio-libs/propcache
  summary: Accelerated property cache
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/aio-libs/propcache
  doc_url: https://propcache.readthedocs.io
  description: The module provides a fast implementation of cached properties for Python 3.9+.

extra:
  recipe-maintainers:
    - xhochy
